import type { Model } from "@/stores/chat-state.svelte";

export const mockModels: Model[] = [
	// OpenAI LLM Models
	{ id: "gpt-4o", provider: "openai", name: "GPT-4o", type: "llm" },
	{ id: "gpt-4o-mini", provider: "openai", name: "GPT-4o Mini", type: "llm" },
	{ id: "gpt-4-turbo", provider: "openai", name: "GPT-4 Turbo", type: "llm" },
	{ id: "gpt-4", provider: "openai", name: "GPT-4", type: "llm" },
	{ id: "gpt-3.5-turbo", provider: "openai", name: "GPT-3.5 Turbo", type: "llm" },

	// 302AI LLM Models
	{ id: "gpt-4o", provider: "302ai", name: "GPT-4o", type: "llm" },
	{ id: "gpt-4o-mini", provider: "302ai", name: "GPT-4o Mini", type: "llm" },
	{ id: "gpt-4-turbo", provider: "302ai", name: "GPT-4 Turbo", type: "llm" },
	{ id: "gpt-4", provider: "302ai", name: "GPT-4", type: "llm" },
	{ id: "gpt-3.5-turbo", provider: "302ai", name: "GPT-3.5 Turbo", type: "llm" },
	{ id: "claude-3-5-sonnet-20241022", provider: "302ai", name: "Claude 3.5 Sonnet", type: "llm" },
	{ id: "claude-3-5-haiku-20241022", provider: "302ai", name: "Claude 3.5 Haiku", type: "llm" },
	{ id: "claude-3-opus-20240229", provider: "302ai", name: "Claude 3 Opus", type: "llm" },
	{ id: "claude-3-sonnet-20240229", provider: "302ai", name: "Claude 3 Sonnet", type: "llm" },
	{ id: "claude-3-haiku-20240307", provider: "302ai", name: "Claude 3 Haiku", type: "llm" },
	{ id: "gemini-1.5-pro-latest", provider: "302ai", name: "Gemini 1.5 Pro", type: "llm" },
	{ id: "gemini-1.5-flash", provider: "302ai", name: "Gemini 1.5 Flash", type: "llm" },
	{ id: "gemini-1.0-pro", provider: "302ai", name: "Gemini 1.0 Pro", type: "llm" },
	{ id: "llama-3.2-90b-instruct", provider: "302ai", name: "Llama 3.2 90B Instruct", type: "llm" },
	{ id: "llama-3.2-11b-instruct", provider: "302ai", name: "Llama 3.2 11B Instruct", type: "llm" },
	{ id: "llama-3.2-3b-instruct", provider: "302ai", name: "Llama 3.2 3B Instruct", type: "llm" },
	{
		id: "llama-3.1-405b-instruct",
		provider: "302ai",
		name: "Llama 3.1 405B Instruct",
		type: "llm",
	},
	{ id: "llama-3.1-70b-instruct", provider: "302ai", name: "Llama 3.1 70B Instruct", type: "llm" },
	{ id: "llama-3.1-8b-instruct", provider: "302ai", name: "Llama 3.1 8B Instruct", type: "llm" },
	{ id: "mixtral-8x7b-instruct", provider: "302ai", name: "Mixtral 8x7B Instruct", type: "llm" },
	{ id: "mistral-7b-instruct", provider: "302ai", name: "Mistral 7B Instruct", type: "llm" },
	{ id: "qwen-2.5-72b-instruct", provider: "302ai", name: "Qwen 2.5 72B Instruct", type: "llm" },
	{ id: "qwen-2.5-32b-instruct", provider: "302ai", name: "Qwen 2.5 32B Instruct", type: "llm" },
	{ id: "qwen-2.5-14b-instruct", provider: "302ai", name: "Qwen 2.5 14B Instruct", type: "llm" },
	{ id: "qwen-2.5-7b-instruct", provider: "302ai", name: "Qwen 2.5 7B Instruct", type: "llm" },
	{ id: "deepseek-v2.5", provider: "302ai", name: "DeepSeek V2.5", type: "llm" },
	{ id: "deepseek-coder-v2", provider: "302ai", name: "DeepSeek Coder V2", type: "llm" },
	{ id: "yi-lightning", provider: "302ai", name: "Yi Lightning", type: "llm" },
	{ id: "yi-large", provider: "302ai", name: "Yi Large", type: "llm" },
	{ id: "yi-medium", provider: "302ai", name: "Yi Medium", type: "llm" },
	{ id: "moonshot-v1-8k", provider: "302ai", name: "Moonshot v1 8K", type: "llm" },
	{ id: "moonshot-v1-32k", provider: "302ai", name: "Moonshot v1 32K", type: "llm" },
	{ id: "moonshot-v1-128k", provider: "302ai", name: "Moonshot v1 128K", type: "llm" },
	{ id: "glm-4-plus", provider: "302ai", name: "GLM-4 Plus", type: "llm" },
	{ id: "glm-4-0520", provider: "302ai", name: "GLM-4 0520", type: "llm" },
	{ id: "glm-4-air", provider: "302ai", name: "GLM-4 Air", type: "llm" },
	{ id: "glm-4-airx", provider: "302ai", name: "GLM-4 AirX", type: "llm" },
	{ id: "glm-4-flash", provider: "302ai", name: "GLM-4 Flash", type: "llm" },
	{ id: "baichuan2-turbo", provider: "302ai", name: "Baichuan2 Turbo", type: "llm" },
	{ id: "baichuan2-turbo-192k", provider: "302ai", name: "Baichuan2 Turbo 192K", type: "llm" },
	{ id: "doubao-pro-32k", provider: "302ai", name: "Doubao Pro 32K", type: "llm" },
	{ id: "doubao-pro-128k", provider: "302ai", name: "Doubao Pro 128K", type: "llm" },
	{ id: "doubao-lite-32k", provider: "302ai", name: "Doubao Lite 32K", type: "llm" },
	{ id: "doubao-lite-128k", provider: "302ai", name: "Doubao Lite 128K", type: "llm" },

	// OpenAI TTS Models
	{ id: "tts-1", provider: "openai", name: "TTS-1", type: "tts" },
	{ id: "tts-1-hd", provider: "openai", name: "TTS-1 HD", type: "tts" },

	// 302AI TTS Models
	{ id: "azure-tts", provider: "302ai", name: "Azure TTS", type: "tts" },
	{ id: "elevenlabs-tts", provider: "302ai", name: "ElevenLabs TTS", type: "tts" },
	{ id: "edge-tts", provider: "302ai", name: "Edge TTS", type: "tts" },
	{ id: "google-tts", provider: "302ai", name: "Google TTS", type: "tts" },
	{ id: "amazon-polly", provider: "302ai", name: "Amazon Polly", type: "tts" },
	{ id: "watson-tts", provider: "302ai", name: "Watson TTS", type: "tts" },
	{ id: "fish-speech", provider: "302ai", name: "Fish Speech", type: "tts" },
	{ id: "coqui-tts", provider: "302ai", name: "Coqui TTS", type: "tts" },

	// OpenAI Text Embedding Models
	{
		id: "text-embedding-ada-002",
		provider: "openai",
		name: "Text Embedding Ada 002",
		type: "text-embedding",
	},
	{
		id: "text-embedding-3-small",
		provider: "openai",
		name: "Text Embedding 3 Small",
		type: "text-embedding",
	},
	{
		id: "text-embedding-3-large",
		provider: "openai",
		name: "Text Embedding 3 Large",
		type: "text-embedding",
	},

	// 302AI Text Embedding Models
	{
		id: "text-multilingual-embedding-002",
		provider: "302ai",
		name: "Text Multilingual Embedding 002",
		type: "text-embedding",
	},
	{ id: "bge-large-zh-v1.5", provider: "302ai", name: "BGE Large ZH v1.5", type: "text-embedding" },
	{ id: "bge-base-zh-v1.5", provider: "302ai", name: "BGE Base ZH v1.5", type: "text-embedding" },
	{ id: "bge-small-zh-v1.5", provider: "302ai", name: "BGE Small ZH v1.5", type: "text-embedding" },
	{ id: "m3e-base", provider: "302ai", name: "M3E Base", type: "text-embedding" },
	{ id: "m3e-large", provider: "302ai", name: "M3E Large", type: "text-embedding" },
	{
		id: "text2vec-base-chinese",
		provider: "302ai",
		name: "Text2Vec Base Chinese",
		type: "text-embedding",
	},
	{
		id: "text2vec-large-chinese",
		provider: "302ai",
		name: "Text2Vec Large Chinese",
		type: "text-embedding",
	},
	{
		id: "sentence-transformers",
		provider: "302ai",
		name: "Sentence Transformers",
		type: "text-embedding",
	},
	{
		id: "universal-sentence-encoder",
		provider: "302ai",
		name: "Universal Sentence Encoder",
		type: "text-embedding",
	},
	{
		id: "cohere-embed-multilingual",
		provider: "302ai",
		name: "Cohere Embed Multilingual",
		type: "text-embedding",
	},
	{ id: "voyage-large-2", provider: "302ai", name: "Voyage Large 2", type: "text-embedding" },
	{ id: "voyage-code-2", provider: "302ai", name: "Voyage Code 2", type: "text-embedding" },

	// 302AI Rerank Models
	{
		id: "cohere-rerank-multilingual",
		provider: "302ai",
		name: "Cohere Rerank Multilingual",
		type: "rerank",
	},
	{ id: "cohere-rerank-english", provider: "302ai", name: "Cohere Rerank English", type: "rerank" },
	{ id: "bge-reranker-large", provider: "302ai", name: "BGE Reranker Large", type: "rerank" },
	{ id: "bge-reranker-base", provider: "302ai", name: "BGE Reranker Base", type: "rerank" },
	{ id: "bge-reranker-v2-m3", provider: "302ai", name: "BGE Reranker v2 M3", type: "rerank" },
	{ id: "jina-reranker-v1", provider: "302ai", name: "Jina Reranker v1", type: "rerank" },
	{ id: "voyage-rerank-lite", provider: "302ai", name: "Voyage Rerank Lite", type: "rerank" },
	{
		id: "cross-encoder-ms-marco",
		provider: "302ai",
		name: "Cross Encoder MS Marco",
		type: "rerank",
	},
	{ id: "rankllama", provider: "302ai", name: "RankLLaMA", type: "rerank" },
	{ id: "colbert-v2", provider: "302ai", name: "ColBERT v2", type: "rerank" },

	// OpenAI Speech to Text Models
	{ id: "whisper-1", provider: "openai", name: "Whisper-1", type: "speech-to-text" },

	// 302AI Speech to Text Models
	{ id: "whisper-large-v3", provider: "302ai", name: "Whisper Large v3", type: "speech-to-text" },
	{ id: "whisper-medium", provider: "302ai", name: "Whisper Medium", type: "speech-to-text" },
	{ id: "whisper-small", provider: "302ai", name: "Whisper Small", type: "speech-to-text" },
	{ id: "whisper-base", provider: "302ai", name: "Whisper Base", type: "speech-to-text" },
	{ id: "whisper-tiny", provider: "302ai", name: "Whisper Tiny", type: "speech-to-text" },
	{
		id: "azure-speech-to-text",
		provider: "302ai",
		name: "Azure Speech to Text",
		type: "speech-to-text",
	},
	{
		id: "google-speech-to-text",
		provider: "302ai",
		name: "Google Speech to Text",
		type: "speech-to-text",
	},
	{ id: "amazon-transcribe", provider: "302ai", name: "Amazon Transcribe", type: "speech-to-text" },
	{
		id: "watson-speech-to-text",
		provider: "302ai",
		name: "Watson Speech to Text",
		type: "speech-to-text",
	},
	{ id: "deepgram-nova-2", provider: "302ai", name: "Deepgram Nova 2", type: "speech-to-text" },
	{ id: "assemblyai-best", provider: "302ai", name: "AssemblyAI Best", type: "speech-to-text" },
	{ id: "sensevoice-small", provider: "302ai", name: "SenseVoice Small", type: "speech-to-text" },
	{ id: "faster-whisper", provider: "302ai", name: "Faster Whisper", type: "speech-to-text" },
	{ id: "whisper-cpp", provider: "302ai", name: "Whisper.cpp", type: "speech-to-text" },
	{ id: "wav2vec2", provider: "302ai", name: "Wav2Vec2", type: "speech-to-text" },
	{ id: "conformer", provider: "302ai", name: "Conformer", type: "speech-to-text" },
	{ id: "deepspeech", provider: "302ai", name: "DeepSpeech", type: "speech-to-text" },
	{ id: "paraformer", provider: "302ai", name: "Paraformer", type: "speech-to-text" },
	{ id: "funasr", provider: "302ai", name: "FunASR", type: "speech-to-text" },
];
