import type { Model, Provider } from "@/types/chat";
import { nanoid } from "nanoid";
const providers: Record<string, Provider> = {
	openai: { id: nanoid(), name: "OpenAI" },
	"302ai": { id: nanoid(), name: "302.AI" },
	anthropic: { id: nanoid(), name: "Anthropic" },
	google: { id: nanoid(), name: "Google" },
};

export const mockModels: Model[] = [
	{ id: nanoid(), provider: providers.openai, name: "gpt-4o", type: "llm" },
	{ id: nanoid(), provider: providers.openai, name: "gpt-4o-mini", type: "llm" },
	{ id: nanoid(), provider: providers.openai, name: "gpt-4-turbo", type: "llm" },
	{ id: nanoid(), provider: providers.openai, name: "gpt-4", type: "llm" },
	{ id: nanoid(), provider: providers.openai, name: "gpt-3.5-turbo", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "gpt-4o", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "gpt-4o-mini", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "gpt-4-turbo", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "gpt-4", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "gpt-3.5-turbo", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "claude-3-5-sonnet-20241022", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "claude-3-5-haiku-20241022", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "claude-3-opus-20240229", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "claude-3-sonnet-20240229", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "claude-3-haiku-20240307", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "gemini-1.5-pro-latest", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "gemini-1.5-flash", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "gemini-1.0-pro", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "llama-3.2-90b-instruct", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "llama-3.2-11b-instruct", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "llama-3.2-3b-instruct", type: "llm" },
	{
		id: nanoid(),
		provider: providers["302ai"],
		name: "llama-3.1-405b-instruct",
		type: "llm",
	},
	{ id: nanoid(), provider: providers["302ai"], name: "llama-3.1-70b-instruct", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "llama-3.1-8b-instruct", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "mixtral-8x7b-instruct", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "mistral-7b-instruct", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "qwen-2.5-72b-instruct", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "qwen-2.5-32b-instruct", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "qwen-2.5-14b-instruct", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "qwen-2.5-7b-instruct", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "deepseek-v2.5", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "deepseek-coder-v2", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "yi-lightning", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "yi-large", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "yi-medium", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "moonshot-v1-8k", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "moonshot-v1-32k", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "moonshot-v1-128k", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "glm-4-plus", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "glm-4-0520", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "glm-4-air", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "glm-4-airx", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "glm-4-flash", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "baichuan2-turbo", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "baichuan2-turbo-192k", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "doubao-pro-32k", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "doubao-pro-128k", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "doubao-lite-32k", type: "llm" },
	{ id: nanoid(), provider: providers["302ai"], name: "doubao-lite-128k", type: "llm" },
	{ id: nanoid(), provider: providers.openai, name: "tts-1", type: "tts" },
	{ id: nanoid(), provider: providers.openai, name: "tts-1-hd", type: "tts" },
	{ id: nanoid(), provider: providers["302ai"], name: "azure-tts", type: "tts" },
	{ id: nanoid(), provider: providers["302ai"], name: "elevenlabs-tts", type: "tts" },
	{ id: nanoid(), provider: providers["302ai"], name: "edge-tts", type: "tts" },
	{ id: nanoid(), provider: providers["302ai"], name: "google-tts", type: "tts" },
	{ id: nanoid(), provider: providers["302ai"], name: "amazon-polly", type: "tts" },
	{ id: nanoid(), provider: providers["302ai"], name: "watson-tts", type: "tts" },
	{ id: nanoid(), provider: providers["302ai"], name: "fish-speech", type: "tts" },
	{ id: nanoid(), provider: providers["302ai"], name: "coqui-tts", type: "tts" },
	{
		id: nanoid(),
		provider: providers.openai,
		name: "text-embedding-ada-002",
		type: "text-embedding",
	},
	{
		id: nanoid(),
		provider: providers.openai,
		name: "text-embedding-3-small",
		type: "text-embedding",
	},
	{
		id: nanoid(),
		provider: providers.openai,
		name: "text-embedding-3-large",
		type: "text-embedding",
	},
	{
		id: nanoid(),
		provider: providers["302ai"],
		name: "text-multilingual-embedding-002",
		type: "text-embedding",
	},
	{ id: nanoid(), provider: providers["302ai"], name: "bge-large-zh-v1.5", type: "text-embedding" },
	{ id: nanoid(), provider: providers["302ai"], name: "bge-base-zh-v1.5", type: "text-embedding" },
	{ id: nanoid(), provider: providers["302ai"], name: "bge-small-zh-v1.5", type: "text-embedding" },
	{ id: nanoid(), provider: providers["302ai"], name: "m3e-base", type: "text-embedding" },
	{ id: nanoid(), provider: providers["302ai"], name: "m3e-large", type: "text-embedding" },
	{
		id: nanoid(),
		provider: providers["302ai"],
		name: "text2vec-base-chinese",
		type: "text-embedding",
	},
	{
		id: nanoid(),
		provider: providers["302ai"],
		name: "text2vec-large-chinese",
		type: "text-embedding",
	},
	{
		id: nanoid(),
		provider: providers["302ai"],
		name: "sentence-transformers",
		type: "text-embedding",
	},
	{
		id: nanoid(),
		provider: providers["302ai"],
		name: "universal-sentence-encoder",
		type: "text-embedding",
	},
	{
		id: nanoid(),
		provider: providers["302ai"],
		name: "cohere-embed-multilingual",
		type: "text-embedding",
	},
	{ id: nanoid(), provider: providers["302ai"], name: "voyage-large-2", type: "text-embedding" },
	{ id: nanoid(), provider: providers["302ai"], name: "voyage-code-2", type: "text-embedding" },
	{
		id: nanoid(),
		provider: providers["302ai"],
		name: "cohere-rerank-multilingual",
		type: "rerank",
	},
	{ id: nanoid(), provider: providers["302ai"], name: "cohere-rerank-english", type: "rerank" },
	{ id: nanoid(), provider: providers["302ai"], name: "bge-reranker-large", type: "rerank" },
	{ id: nanoid(), provider: providers["302ai"], name: "bge-reranker-base", type: "rerank" },
	{ id: nanoid(), provider: providers["302ai"], name: "bge-reranker-v2-m3", type: "rerank" },
	{ id: nanoid(), provider: providers["302ai"], name: "jina-reranker-v1", type: "rerank" },
	{ id: nanoid(), provider: providers["302ai"], name: "voyage-rerank-lite", type: "rerank" },
	{
		id: nanoid(),
		provider: providers["302ai"],
		name: "cross-encoder-ms-marco",
		type: "rerank",
	},
	{ id: nanoid(), provider: providers["302ai"], name: "rankllama", type: "rerank" },
	{ id: nanoid(), provider: providers["302ai"], name: "colbert-v2", type: "rerank" },
	{ id: nanoid(), provider: providers.openai, name: "whisper-1", type: "speech-to-text" },
	{ id: nanoid(), provider: providers["302ai"], name: "whisper-large-v3", type: "speech-to-text" },
	{ id: nanoid(), provider: providers["302ai"], name: "whisper-medium", type: "speech-to-text" },
	{ id: nanoid(), provider: providers["302ai"], name: "whisper-small", type: "speech-to-text" },
	{ id: nanoid(), provider: providers["302ai"], name: "whisper-base", type: "speech-to-text" },
	{ id: nanoid(), provider: providers["302ai"], name: "whisper-tiny", type: "speech-to-text" },
	{
		id: nanoid(),
		provider: providers["302ai"],
		name: "azure-speech-to-text",
		type: "speech-to-text",
	},
	{
		id: nanoid(),
		provider: providers["302ai"],
		name: "google-speech-to-text",
		type: "speech-to-text",
	},
	{ id: nanoid(), provider: providers["302ai"], name: "amazon-transcribe", type: "speech-to-text" },
	{
		id: nanoid(),
		provider: providers["302ai"],
		name: "watson-speech-to-text",
		type: "speech-to-text",
	},
	{ id: nanoid(), provider: providers["302ai"], name: "deepgram-nova-2", type: "speech-to-text" },
	{ id: nanoid(), provider: providers["302ai"], name: "assemblyai-best", type: "speech-to-text" },
	{ id: nanoid(), provider: providers["302ai"], name: "sensevoice-small", type: "speech-to-text" },
	{ id: nanoid(), provider: providers["302ai"], name: "faster-whisper", type: "speech-to-text" },
	{ id: nanoid(), provider: providers["302ai"], name: "whisper-cpp", type: "speech-to-text" },
	{ id: nanoid(), provider: providers["302ai"], name: "wav2vec2", type: "speech-to-text" },
	{ id: nanoid(), provider: providers["302ai"], name: "conformer", type: "speech-to-text" },
	{ id: nanoid(), provider: providers["302ai"], name: "deepspeech", type: "speech-to-text" },
	{ id: nanoid(), provider: providers["302ai"], name: "paraformer", type: "speech-to-text" },
	{ id: nanoid(), provider: providers["302ai"], name: "funasr", type: "speech-to-text" },
];
