import type { ModelProvider } from "$lib/types/provider.js";

export const DEFAULT_PROVIDERS: ModelProvider[] = [
	{
		id: "302AI",
		name: "302.AI",
		apiType: "302ai",
		apiKey: "",
		baseUrl: "https://api.302.ai/v1",
		enabled: true,
		custom: false,
		status: "pending",
		websites: {
			official: "https://302.ai/",
			apiKey: "https://dash.302.ai/apis/list",
			docs: "https://302ai.apifox.cn/",
			models: "https://302ai.apifox.cn/api-147522038",
			defaultBaseUrl: "https://api.302.ai/v1",
		},
	},
	{
		id: "openai",
		name: "OpenAI",
		apiType: "openai",
		apiKey: "",
		baseUrl: "https://api.openai.com/v1",
		enabled: true,
		custom: false,
		status: "pending",
		websites: {
			official: "https://openai.com/",
			apiKey: "https://platform.openai.com/api-keys",
			docs: "https://platform.openai.com/docs",
			models: "https://platform.openai.com/docs/models",
			defaultBaseUrl: "https://api.openai.com/v1",
		},
	},
	{
		id: "anthropic",
		name: "Anthropic",
		apiType: "anthropic",
		apiKey: "",
		baseUrl: "https://api.anthropic.com",
		enabled: true,
		custom: false,
		status: "pending",
		websites: {
			official: "https://www.anthropic.com/",
			apiKey: "https://console.anthropic.com/settings/keys",
			docs: "https://docs.anthropic.com/",
			models: "https://docs.anthropic.com/claude/docs/models-overview",
			defaultBaseUrl: "https://api.anthropic.com",
		},
	},
	{
		id: "google",
		name: "Google AI",
		apiType: "gemini",
		apiKey: "",
		baseUrl: "https://generativelanguage.googleapis.com",
		enabled: true,
		custom: false,
		status: "pending",
		websites: {
			official: "https://gemini.google.com/",
			apiKey: "https://aistudio.google.com/app/apikey",
			docs: "https://ai.google.dev/gemini-api/docs",
			models: "https://ai.google.dev/gemini-api/docs/models/gemini",
			defaultBaseUrl: "https://generativelanguage.googleapis.com",
		},
	},
];
